---
default_language_version:
  python: python3.11
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.1
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']
    exclude: templates     # Exclude this due to helm template syntax not being valid yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
  - id: ruff
    args: [--fix, --extend-select, I]
  - id: ruff-format
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
    files: containerize/.*$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.0
  hooks:
  - id: mypy
    args: [--config-file=mypy.ini, --explicit-package-bases]
    name: mypy (poetry)
    language: system
    types_or: [python, cython]
    entry: uv run mypy
